networks:
  public:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 8.40.27.0/24
services:
  victim:
    container_name: victim
    build: ./victim
    networks:
      public:
        ipv4_address: 8.40.27.10
  c2c:
    build: ./c2c
    container_name: c2c
    networks:
      public:
        ipv4_address: 8.40.27.100